language: node_js

node_js:
- '8'

sudo: false

#script:
#- npm run test

deploy:
- provider: npm
  email: 'devmonk@mediamonks.com'
  api_key: $NPM_TOKEN
  on:
    tags: true
    node: '8'
  skip_cleanup: true
